version = "2"

[run]
timeout = "5m"
tests = true

[formatters]
enable = ["gofumpt", "gci"]

[linters]
enable = [
    "bodyclose",
    "errcheck",
    "goconst",
    "gocritic",
    "gomoddirectives",
    "gosec",
    "govet",
    "staticcheck",
]

[formatters.settings.gofumpt]
extra-rules = true
